-- -- Gotta change the config in `~/.local/share/nvim/site/pack/packer/start/cord.nvim` folder, changing this one wont work.
--
-- require('cord').setup {
--     usercmds = true,
--     log_level = 'error',
--     timer = {
--         interval = 1500,
--         reset_on_idle = false,
--         reset_on_change = false,
--     },
--     editor = {
--         image = nil,
--         client = 'neovim',
--         tooltip = 'The Superior Text Editor for the Chads',
--     },
--     display = {
--         show_time = true,
--         show_repository = true,
--         show_cursor_position = false,
--         swap_fields = false,
--         swap_icons = false,
--         workspace_blacklist = {},
--     },
--     lsp = {
--         show_problem_count = true,
--         severity = 1,
--         scope = 'workspace',
--     },
--     idle = {
--         enable = true,
--         show_status = true,
--         timeout = 600000,
--         disable_on_focus = false,
--         text = 'Touching grass...',
--         tooltip = '💤',
--     },
--     text = {
--         viewing = 'Viewing {}',
--         editing = 'Editing {}',
--         file_browser = 'Browsing files in {}',
--         plugin_manager = 'Managing plugins in {}',
--         lsp_manager = 'Configuring LSP in {}',
--         vcs = 'Committing changes in {}',
--         workspace = 'In {}',
--     },
--     buttons = {
--         {
--             label = 'View Repository',
--             url = 'git',
--         },
--     },
--     assets = nil,
-- }
